/**
 * WhiskyCompass content publisher
 *
 * Usage:
 *   set RAKUTEN_APP_ID=...
 *   set RAKUTEN_ACCESS_KEY=...
 *   set RAKUTEN_AFFILIATE_ID=...
 *   set AMAZON_TAG=yourtag-22
 *   node app.js
 *
 * This program only writes generated product data to public/data/whiskies.js.
 * The credentials stay in environment variables and are never written to public.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

const LM_STUDIO_API_URL = 'http://localhost:1234/v1/chat/completions';
const OUTPUT_FILE = path.resolve('public/data/whiskies.js');
const RAKUTEN_ENDPOINT = 'https://openapi.rakuten.co.jp/ichibams/api/IchibaItem/Search/20260701';
const RAKUTEN_WHISKY_GENRE_ID = '100330';
const RAKUTEN_APP_ID = process.env.RAKUTEN_APP_ID;
const RAKUTEN_ACCESS_KEY = process.env.RAKUTEN_ACCESS_KEY;
const RAKUTEN_AFFILIATE_ID = process.env.RAKUTEN_AFFILIATE_ID;
const RAKUTEN_REFERRER = process.env.RAKUTEN_REFERRER || 'https://whisky-compass.pikumin.workers.dev/';
const RAKUTEN_ORIGIN = new URL(RAKUTEN_REFERRER).origin;
const AMAZON_TAG = process.env.AMAZON_TAG || 'yourtag-22';
const AI_MODEL_NAME = process.env.LM_STUDIO_MODEL || undefined;

function required(value, name) {
  if (!value) throw new Error(`${name} is not set. See the comment at the top of app.js.`);
  return value;
}

function cleanTitle(value = '') {
  return value.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim();
}

function slugify(text = '') {
  return cleanTitle(text).toLowerCase().replace(/[^a-z0-9\u3040-\u30ff\u4e00-\u9faf]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80);
}

function tagsFor(title, caption = '') {
  const text = `${title} ${caption}`.toLowerCase();
  const tags = [];
  if (/アイラ|ラフロイグ|アードベッグ|ボウモア|ピート|スモーキー/.test(text)) tags.push('スモーキー');
  if (/バーボン|メーカーズ|ワイルドターキー/.test(text)) tags.push('バニラ', 'リッチ');
  if (/白州|山崎|余市|宮城峡|響|知多|ジャパニーズ/.test(text)) tags.push('華やか', 'フルーティー');
  if (/シェリー|マッカラン|グレン/.test(text)) tags.push('フルーティー', 'リッチ');
  return [...new Set(tags.length ? tags : ['リッチ', 'フルーティー'])].slice(0, 3);
}

function styleFor(title) {
  if (/バーボン|メーカーズ|ワイルドターキー/.test(title)) return ['バーボン'];
  if (/白州|山崎|余市|宮城峡|響|知多|嘉之助|厚岸/.test(title)) return ['ジャパニーズ', 'ハイボール'];
  return ['スコッチ'];
}

function extractOrigin(item) {
  const text = cleanTitle(`${item.itemName} ${item.itemCaption || ''}`);
  const countryPatterns = [
    {regex: /イギリス産|英国産|スコットランド産|アイラ|スペイサイド|ハイランド|ローランド|スコッチ/i, label: 'イギリス産'},
    {regex: /日本産|国産|日本製|ジャパニーズ|サントリー|ニッカ|竹鶴|山崎|白州|響|知多|余市|宮城峡/i, label: '日本産'},
    {regex: /アメリカ産|米国産|アメリカ|USA|U\.S\.|ケンタッキー|バーボン/i, label: 'アメリカ産'},
    {regex: /カナダ産|カナディア|カナダ/i, label: 'カナダ産'},
    {regex: /アイルランド産|アイルランド|アイリッシュ/i, label: 'アイルランド産'},
    {regex: /フランス産|フランス/i, label: 'フランス産'}
  ];
  const brandPatterns = [
    'サントリー', 'ニッカ', '山崎', '白州', '響', '知多', '余市', '宮城峡', '竹鶴',
    'ザ・マッカラン', 'マッカラン', 'ラフロイグ', 'ボウモア', 'メーカーズマーク',
    'ジャックダニエル', 'バランタイン', 'ボウモア', 'タリスカー', 'ジョニーウォーカー',
    'ヘネシー', 'グレンフィディック', 'グレンリベット', 'アードベッグ', 'カナディアンクラブ'
  ];
  const country = countryPatterns.find(p => p.regex.test(text))?.label || '';
  let brand = '';
  for (const candidate of brandPatterns) {
    const regex = new RegExp(candidate.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&'), 'i');
    if (regex.test(text)) {
      brand = candidate;
      break;
    }
  }
  if (!brand && item.shopName && !/rakuten/i.test(item.shopName)) {
    brand = item.shopName;
  }
  if (!country && /ウイスキー|シングルモルト|バーボン|ジャパニーズ|スコッチ/i.test(text)) {
    brand = brand || item.shopName || '';
  }
  return [country || '原産国不明', brand || 'ブランド不明'].join(' / ');
}

function amazonSearchUrl(title) {
  return `https://www.amazon.co.jp/s?k=${encodeURIComponent(title)}&tag=${encodeURIComponent(AMAZON_TAG)}`;
}

function canonicalTitle(text = '') {
  return cleanTitle(text).toLowerCase().replace(/\s+/g, ' ');
}

async function loadExistingProducts() {
  try {
    const text = await fs.readFile(OUTPUT_FILE, 'utf8');
    const match = text.match(/window\.WHISKY_DATA\s*=\s*(\[[\s\S]*\]);?/m);
    return match ? JSON.parse(match[1]) : [];
  } catch (error) {
    if (error.code === 'ENOENT') return [];
    throw error;
  }
}

function writeProducts(products) {
  const payload = `// Generated by ../app.js at ${new Date().toISOString()}. Do not edit manually.\nwindow.WHISKY_DATA = ${JSON.stringify(products, null, 2)};\n`;
  return fs.writeFile(OUTPUT_FILE, payload, 'utf8');
}

async function rakutenSearch(sort) {
  const params = new URLSearchParams({
    applicationId: required(RAKUTEN_APP_ID, 'RAKUTEN_APP_ID'),
    accessKey: required(RAKUTEN_ACCESS_KEY, 'RAKUTEN_ACCESS_KEY'),
    affiliateId: RAKUTEN_AFFILIATE_ID || '',
    keyword: 'ウイスキー',
    genreId: RAKUTEN_WHISKY_GENRE_ID,
    hits: '2',
    page: '1',
    sort,
    availability: '1',
    imageFlag: '1',
    format: 'json',
    formatVersion: '2',
    elements: 'itemName,itemPrice,itemCaption,itemUrl,affiliateUrl,mediumImageUrls,reviewCount,reviewAverage,shopName,genreId,availability'
  });
  for (let attempt = 0; attempt < 3; attempt += 1) {
    const response = await fetch(`${RAKUTEN_ENDPOINT}?${params}`, {
      headers: {
        Referer: RAKUTEN_REFERRER,
        Origin: RAKUTEN_ORIGIN
      }
    });
    if (response.ok) {
      const data = await response.json();
      const items = Array.isArray(data.items)
        ? data.items
        : Array.isArray(data.Items)
          ? data.Items.map(entry => entry.item || entry.Item || entry)
          : [];
      console.log(`Rakuten search (${sort}): ${items.length} items`);
      return items;
    }
    const text = await response.text();
    if (response.status === 429) {
      const retryAfter = Number(response.headers.get('retry-after')) || 1;
      console.warn(`Rakuten rate limited, retrying in ${retryAfter}s (${attempt + 1}/3)`);
      await new Promise(resolve => setTimeout(resolve, retryAfter * 1000));
      continue;
    }
    throw new Error(`Rakuten API ${response.status}: ${text}`);
  }
  throw new Error('Rakuten API rate limit retry exhausted');
  // formatVersion=2 is documented as `items`, but retain compatibility with
  // older response wrappers so a valid response is never silently discarded.
  const items = Array.isArray(data.items)
    ? data.items
    : Array.isArray(data.Items)
      ? data.Items.map(entry => entry.item || entry.Item || entry)
      : [];
  console.log(`Rakuten search (${sort}): ${items.length} items`);
  return items;
}

function isBottle(item) {
  const title = cleanTitle(item.itemName);
  const text = `${title} ${item.itemCaption || ''}`;
  const whiskyName = /ウイスキー|ウィスキー|whisk(?:e)?y|スコッチ|バーボン|シングルモルト|ピュアモルト|ブレンデッド|竹鶴|山崎|白州|知多|余市|宮城峡|響|角瓶|ニッカ/i;
  const nonWhiskyProduct = /炭酸水|ソーダ|割[り材]|ボールペン|筆記具|ジェットストリーム|スキットル|ウ[ィイ]スキーボトル|水筒|アクセサリー|ピアス|コニャッククォーツ|ハイボール.*缶|缶.*ハイボール|リキュール.*発泡/i;
  if (!whiskyName.test(title) || nonWhiskyProduct.test(text)) return false;
  // Do not use a broad "本" check here: whisky listings commonly say "700ml 1本".
  return !/グラス|タンブラー|チョコ|ケーキ|ハイボール缶|セット.*グラス|ソーダ|文庫|単行本|書籍|漫画|くじ/i.test(text);
}

function normaliseRakutenItem(item, source, index) {
  const title = cleanTitle(item.itemName);
  const image = item.mediumImageUrls?.[0]?.imageUrl || '';
  return {
    id: `rakuten-${item.itemCode || `${source}-${index}`}`.replace(/[^a-zA-Z0-9_-]/g, '-'),
    slug: slugify(title + '-' + (item.itemCode || index)),
    name: title,
    origin: extractOrigin(item),
    score: Number(item.reviewAverage || 0).toFixed(1),
    price: Number(item.itemPrice || 0),
    flavor: tagsFor(title, item.itemCaption),
    style: styleFor(title),
    caption: cleanTitle(item.itemCaption || ''),
    note: '',
    label: title.slice(0, 14).toUpperCase(),
    image,
    amazon: amazonSearchUrl(title),
    rakuten: item.affiliateUrl || item.itemUrl,
    source,
    reviewCount: Number(item.reviewCount || 0),
    updatedAt: new Date().toISOString()
  };
}



function formatArticleTitle(item) {
  const original = cleanTitle(item.name || '');
  const ageMatch = original.match(/\d{1,2}(?:\.\d+)?\s*(?:年|歳|Y|y|yr|yrs|years?)/i);
  const capacityMatch = original.match(/\d+(?:\.\d+)?\s*(?:ml|mL|ML|l|L|リットル|㎖|ℓ)/i);
  const age = ageMatch ? ageMatch[0].replace(/\s+/g, '') : '';
  const capacity = capacityMatch ? capacityMatch[0].replace(/\s+/g, '') : '';
  let title = original;
  if (ageMatch) title = title.replace(ageMatch[0], '');
  if (capacityMatch) title = title.replace(capacityMatch[0], '');
  title = title.replace(/【[^】]*】/g, '');
  title = title.replace(/\([^\)]*\)/g, '');
  title = title.replace(/\[[^\]]*\]/g, '');
  title = title.replace(/(ウイスキー|ウィスキー|シングルモルト|ピュアモルト|ブレンデッド|ブレンデッドモルト|ノンエイジ|NA|箱付|正規品|送料無料|ギフト|セット|限定|新品|未開封|特価|中古)/gi, '');
  title = title.replace(/[×x✕*]/g, ' ').replace(/\s+/g, ' ').trim();
  if (!title) title = original;
  return [title, age, capacity].filter(Boolean).join(' ').replace(/\s+/g, ' ');
}

async function createArticle(item) {
  // Use a title fallback from the Rakuten-normalized title, but let LocalLM shape the final article title and body.
  const fallbackTitle = formatArticleTitle(item);
  const fallbackBody = item.note || `${item.name} はおすすめのウイスキーです。詳細は販売ページでご確認ください。`;
  try {
    const prompt = `商品情報:\n名前: ${item.name}\n価格: ${item.price || ''}\n説明: ${item.caption || ''}\nタグ: ${(item.flavor||[]).join('、')}\n\n出力形式: JSON で {"title":"...","body":"..."} のみを返してください。タイトルは「ウイスキー名 銘柄名 熟成年数 容量」の形式を優先して短く、本文は120〜300文字の日本語で説明を書くこと。`;
    const res = await fetch(LM_STUDIO_API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: [{ role: 'system', content: 'あなたは日本語の編集者です。出力は必ずJSONのみで返してください。' }, { role: 'user', content: prompt }], temperature: 0.4 }) });
    if (!res.ok) throw new Error(`LocalLM ${res.status}`);
    const data = await res.json();
    const content = data.choices?.[0]?.message?.content || '';
    // Try to extract JSON from response
    const jsonMatch = content.trim().match(/\{[\s\S]*\}/);
    const parsed = jsonMatch ? JSON.parse(jsonMatch[0]) : null;
    return {
      title: (parsed && parsed.title) ? parsed.title : fallbackTitle,
      body: (parsed && parsed.body) ? parsed.body : fallbackBody
    };
  } catch (err) {
    console.warn('createArticle failed:', err.message);
    return { title: fallbackTitle, body: fallbackBody };
  }
}

async function createReview(item) {
  const fallback = `${item.name}は${item.flavor.join('・')}の印象を楽しみたい方に向く候補です。販売ページで容量・度数・価格をご確認ください。`;
  console.log(`Generating LocalLM review for ${item.name}...`);
  try {
    const response = await fetch(LM_STUDIO_API_URL, {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ...(AI_MODEL_NAME ? { model: AI_MODEL_NAME } : {}), temperature: 0.35,
        messages: [
          { role: 'system', content: 'あなたは日本のウイスキー編集者です。与えられた販売情報だけを根拠に、断定・受賞歴・在庫の主張をせず、80〜120字の中立な紹介文を日本語で作成してください。HTMLは不要です。' },
          { role: 'user', content: `商品名: ${item.name}\n商品説明: ${item.caption || 'なし'}\n価格: ${item.price}円\nレビュー平均: ${item.score}\n想定タグ: ${item.flavor.join('、')}` }
        ]
      })
    });
    if (!response.ok) throw new Error(`LocalLM ${response.status}`);
    const data = await response.json();
    return String(data.choices?.[0]?.message?.content || fallback).replace(/<[^>]*>/g, '').trim().slice(0, 260);
  } catch (error) {
    console.warn(`LocalLM review skipped for ${item.name}: ${error.message}`);
    return fallback;
  }
}

async function main() {
  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  if (!RAKUTEN_APP_ID || !RAKUTEN_ACCESS_KEY) {
    console.warn('Rakuten credentials are not set; preserving the built-in review cards.');
    process.exitCode = 0;
    return;
  }

  const existing = await loadExistingProducts();
  const existingTitles = new Set(existing.map(w => canonicalTitle(w.articleTitle || w.name)));

  const [popularRaw, latestRaw] = await Promise.all([rakutenSearch('-reviewCount'), rakutenSearch('-updateTimestamp')]);
  // Using Rakuten only; Amazon affiliate links will point to Amazon search results based on title
  const seen = new Set();
  const candidates = [
    ...popularRaw.map(x => [x, 'popular']),
    ...latestRaw.map(x => [x, 'latest'])
  ];

  const products = candidates
    .filter(([item]) => isBottle(item))
    .map(([item, source], index) => normaliseRakutenItem(item, source, index))
    .filter(item => item.name && !seen.has(item.name) && seen.add(item.name))
    .slice(0, 60);

  if (products.length === 0) {
    throw new Error(`No publishable whisky products found (popular: ${popularRaw.length}, latest: ${latestRaw.length}). Existing public data was kept.`);
  }

  console.log('\nSelected whisky products:');
  products.forEach((item, index) => {
    console.log(`${String(index + 1).padStart(2, '0')}. [${item.source}] ${item.name} — ¥${item.price.toLocaleString('ja-JP')}`);
  });

  console.log('\n');

  const newProducts = [];
  for (const item of products) {
    const titleKey = canonicalTitle(formatArticleTitle(item));
    if (existingTitles.has(titleKey)) {
      console.log(`Skipping duplicate article title: ${item.name} -> ${formatArticleTitle(item)}`);
      continue;
    }
    item.note = await createReview(item);
    const article = await createArticle(item);
    item.articleTitle = article.title;
    item.articleBody = article.body;
    item.amazon = amazonSearchUrl(item.articleTitle || item.name);
    newProducts.push(item);
    existingTitles.add(canonicalTitle(item.articleTitle || item.name));
  }

  const mergedProducts = [...existing, ...newProducts];
  await writeProducts(mergedProducts);
  console.log(`Published ${newProducts.length} new Rakuten product reviews to ${OUTPUT_FILE} (total ${mergedProducts.length})`);
  console.log(`Published ${products.length} Rakuten product reviews to ${OUTPUT_FILE}`);
}

main().catch(error => { console.error(error); process.exitCode = 1; });
